name: Deployment created
run-name: ${{ github.event.deployment.environment }} - test

on:
  deployment

jobs:
  sample-job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }}
    concurrency: ${{ github.event.deployment.environment }}
    steps:
      - run: echo "it works"